### ISSUE TITLE
Pomodoro Feature To-do List

### ISSUE THREAD

**Issue by Royl0406** [Royl0406/Study-Duel#27]
- [ ] Adding session increment/ decrement to main menu
  - [ ] Need to store initial and remaining # of sessions
- [x] Creating a break page  
  - [x] Transition from break screen back to pomodoro screen
  - [x] Button to start next session  
  - [x] 5-minute timer
- [x] Hooking it up to pomodoro and stats screen
- [x] Transition from pomodoro screen to break screen
  - [x] Only when remaining session > 0
- [ ] Need to store sum of coins earned across sessions --> display at the end but update after each session
- [x] Need a way to abandon the study session

**Comment by Royl0406** [comment]
Main tasks completed. Will create individual issues for minor tasks.
